### ISSUE TITLE
No configparser in Python2

### ISSUE THREAD

**Issue by chenl** [sdague/amt#10]
Commit `94baded9ab19a8ea04ba17bdb9af98ba535d7e7e`, while fixed Python3 support, broke it on Python2:

```
$ amtctrl -h   
Traceback (most recent call last):
  File "/home/chenl/src/amt/.env/bin/amtctrl", line 8, in <module>
    import amt.hostdb
  File "/home/chenl/src/amt/.env/local/lib/python2.7/site-packages/amt/hostdb.py", line 13, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by chenl** [comment]
Fixed by https://github.com/sdague/amt/pull/11
